application: flophase
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /account/.*
  script: net/sf/flophase/account.py

- url: /entry/.*
  script: net/sf/flophase/entry.py

- url: /xaction/.*
  script: net/sf/flophase/xaction.py

- url: /.*
  script: flophase.py

